package it.unipi.dsmt.FitConnect.erlang;

import com.ericsson.otp.erlang.*;

import java.io.IOException;
import java.util.List;

public class ErlangNode {
    private String username;
    private String cookie;
    private String erlangMessanger;
    private String erlangNotifier;
    private String erlangServerMailbox;
    private List<String> courseNames;
    private String mailBoxId;
    private OtpNode userNode;
    private OtpMbox userMail;
    private OtpErlangTuple from;

    // Generates a erlang node used for communication between the erlang server and the user
    public ErlangNode(String username, List<String> courseNames, String cookie, String erlangMessanger, String erlangNotifier, String erlangServerMailbox) throws IOException{
        // All user information and Erlang server information
        this.username = username;
        this.courseNames = courseNames;
        this.cookie = cookie;
        this.erlangMessanger = erlangMessanger;
        this.erlangNotifier = erlangNotifier;
        this.erlangServerMailbox = erlangServerMailbox;

        this.mailBoxId = this.username + "Mail";
        this.userNode = new OtpNode(this.username, this.cookie);
        this.userMail = userNode.createMbox(this.mailBoxId);
        this.from = new OtpErlangTuple(new OtpErlangObject[] {
                this.userMail.self(), this.userNode.createRef() });
    }

    /**
     * Gets the username linked to the node
     * @return Username of the user that owns the node
     */
    public String getNodeName(){
        return this.username;
    }

    /**
     * Sends a message to the fitNotifier to set a new timer
     * @param mode it is either "insert", "edit" or "delete"
     * @param courseName course Id
     * @param personalTrainer username of the personalTrainer, this whould be filled by the caller
     * @param time subtraction between the current time and when the notification must appear (Int)
     */
    private void sendRequestToNotifier(String mode, String username, String courseName, int time){
        OtpErlangAtom msgType = new OtpErlangAtom(mode);
        OtpErlangString user = new OtpErlangString(username);
        OtpErlangString course = new OtpErlangString(courseName);
        OtpErlangInt delay = new OtpErlangInt(time);
        OtpErlangTuple outMsg = new OtpErlangTuple(new OtpErlangObject[]{msgType, user, course, delay});
        OtpErlangObject msg_gen = new OtpErlangTuple(new OtpErlangObject[] {
            new OtpErlangAtom("$gen_call"), this.from, outMsg });
        this.userMail.send(this.erlangNotifier, this.erlangServerMailbox, msg_gen);
    }

    /**
     * Sends a message to the fitMessanger
     * @param msgStructure message generated by any other function of the node
     */
    private void sendRequest(OtpErlangTuple msgStructure) throws OtpErlangExit, OtpErlangDecodeException {
        OtpErlangObject msg_gen = new OtpErlangTuple(new OtpErlangObject[] {
                new OtpErlangAtom("$gen_call"), this.from, msgStructure });
        this.userMail.send(this.erlangMessanger, this.erlangServerMailbox, msg_gen);
    }

    /**
     * Receives a message from the fitMessanger or fitNotifier
     * @return an Array of strings that should be used to identify the nature of the message
     */
    public String[] receive() throws OtpErlangExit, OtpErlangDecodeException {
        OtpErlangObject reply = this.userMail.receive(1000);

        if (reply == null){
            return null;
            //return new String[] {"Error", "Server is down"};
        }

        OtpErlangTuple t = (OtpErlangTuple) reply;
        System.out.println(this.username + "-> Full reply: " + t.toString());
        //OtpErlangTuple msg = (OtpErlangTuple) t.elementAt(1);
        //System.out.println(this.username + "-> Message: " + msg.toString());
        //System.out.println(this.username + "-> Number of elements in message: " + msg.arity());

        //OtpErlangAtom msgType = (OtpErlangAtom) msg.elementAt(0);
        //FIX DEPENDING ON LENGTH
        //OtpErlangObject content = msg.elementAt(1);
        
        //return new String[] { msgType.toString(), content.toString()};
        return new String[] { "xd", "xd"};
    }

    /**
     * Called after collecting all the courses from MongoDb to send to the fitMessanger the clients for the current user
     */
    public void connect() throws OtpErlangExit, OtpErlangDecodeException {
        OtpErlangAtom msgType = new OtpErlangAtom("connect");
        OtpErlangObject[] coursesArray = this.courseNames.stream().map(OtpErlangString::new).toArray(OtpErlangObject[]::new);
        OtpErlangString username = new OtpErlangString(this.username);
        OtpErlangList courses = new OtpErlangList(coursesArray);
        OtpErlangTuple outMsg = new OtpErlangTuple(new OtpErlangObject[]{this.userMail.self(), msgType, courses, username});
        sendRequest(outMsg);
    }
    
    /**
     * Debug function to display clients, users, or courses
     * @param something can either be one of the following: clients, users, or courses
     */
    public void display(String something) throws OtpErlangExit, OtpErlangDecodeException {
        OtpErlangAtom msgType = new OtpErlangAtom(something);
        OtpErlangTuple outMsg = new OtpErlangTuple(new OtpErlangObject[]{msgType});
        sendRequest(outMsg);
    }

    /**
     * Adds a state in the fitMessanger to receive messages and notifications from that course
     * @param courseName name of the course that wants to be joined
     */
    public void joinCourse(String courseName) throws OtpErlangExit, OtpErlangDecodeException {
        OtpErlangAtom msgType = new OtpErlangAtom("joinCourse");
        OtpErlangString course = new OtpErlangString(courseName);
        OtpErlangString username = new OtpErlangString(this.username);
        OtpErlangTuple outMsg = new OtpErlangTuple(new OtpErlangObject[]{msgType, course, username});
        sendRequest(outMsg);
    }

    /**
     * Removes a state in the fitMessanger to stop receiving messages and notifications from that course
     * @param courseName name of the course that wants to be left
     */
    public void leaveCourse(String courseName) throws OtpErlangExit, OtpErlangDecodeException {
        OtpErlangAtom msgType = new OtpErlangAtom("exitCourse");
        OtpErlangString course = new OtpErlangString(courseName);
        OtpErlangString username = new OtpErlangString(this.username);
        OtpErlangTuple outMsg = new OtpErlangTuple(new OtpErlangObject[]{msgType, course, username});
        sendRequest(outMsg);
    }

    /**
     * Sends a broadcast message to a course
     * @param message the text of the message that is being sent
     * @param courseName name of the course that is going to receive the message
     */
    public void sendMessage(String message, String courseName) throws OtpErlangExit, OtpErlangDecodeException {
        OtpErlangAtom msgType = new OtpErlangAtom("sendToCourse");
        OtpErlangString course = new OtpErlangString(courseName);
        OtpErlangString username = new OtpErlangString(this.username);
        OtpErlangString msg = new OtpErlangString(message);
        OtpErlangTuple outMsg = new OtpErlangTuple(new OtpErlangObject[]{msgType, course, username, msg});
        sendRequest(outMsg);
    }

    /**
     * Disconnects the user from the fitMessanger removing all the states of that user
     */
    public void disconnect() throws OtpErlangExit, OtpErlangDecodeException {
        OtpErlangAtom msgType = new OtpErlangAtom("disconnect");
        OtpErlangString username = new OtpErlangString(this.username);
        OtpErlangTuple outMsg = new OtpErlangTuple(new OtpErlangObject[]{msgType, username});
        sendRequest(outMsg);
    }

    /**
     * Starts the node for the user generating 2 threads for the node, a receiver and a sender
     */
    public void startClientNode() {
        ErlangNodeListener myListener = new ErlangNodeListener(this);
        ErlangNodeSender mySender = new ErlangNodeSender(this);
        try {
            myListener.start();
            mySender.start();
            connect();
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println("Something failed.");
        }
    }
    
    // VA RIMOSSO PERCHé GESTITO DA THREAD X OGNI USER
    public void processCommand(String command){
        String[] parts = command.split("-");
        String commandName = parts[0].trim();
        try{
            switch (commandName) {
            case "display": // 1 args: String something = (Users, Courses, Clients)
                display(parts[1].trim());
                break;
            case "join": // 1 args: String courseName
                joinCourse(parts[1].trim());
                break;
            case "disconnect": // 0 args
                disconnect();
                break;
            case "leave": // 1 args: String courseName
                leaveCourse(parts[1].trim());
                break;
            case "send": // 3 args: String message, String receiver
                sendMessage(parts[1].trim(), parts[2].trim());
                break;
            case "i": // 2 args: String mode, String courseName, Int time
                sendRequestToNotifier("insert", this.username, parts[1].trim(),Integer.parseInt(parts[2].trim()));
                break;
            case "e": // 2 args: String mode, String courseName, Int time
                sendRequestToNotifier("edit", this.username, parts[1].trim(),Integer.parseInt(parts[2].trim()));
                break;
            case "d": // 2 args: String mode, String courseName, Int time
                sendRequestToNotifier("delete", this.username, parts[1].trim(), 0);
                break;
            default:
                break;
        }
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println("Something failed.");
        }
    }
}